server:
  port: 9999
spring:
   datasource:
      hikari:
         connectionTimeout: 30000
         idleTimeout: 600000
         maxLifetime: 1800000
         minimumIdle: 10
         maximum-pool-size: 10
      url: jdbc:mysql://localhost:3306/?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Taipei&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: 
      driver-class-name: com.mysql.jdbc.Driver
   jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
      hibernate:
         ddl-auto: none